name: Gatsby Publish

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          contentful-spaceid: ${{ secrets.CONTENTFUL_SPACEID }}
          contentful-access-token: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          deploy-branch: master