name: Gatsby Publish

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          CONTENTFUL_SPACEID: ${{ secrets.CONTENTFUL_SPACEID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          NODE_ENV: production
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: master